<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GadgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GadgetRepository extends EntityRepository
{
    public function getFindAllGadgetsQuery()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT g FROM ShopBundle:Gadget g'
            );

        return $query;
    }

    public function getSearchQuery($needle)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT g FROM ShopBundle:Gadget g WHERE g.title like :needle or g.manufacturer like :needle"
            )
            ->setParameter('needle', "%$needle%");

        return $query;
    }
}
