<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * GadgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GadgetRepository extends EntityRepository
{
    public function findAllGadgets($page)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT g FROM ShopBundle:Gadget g'
            );
        $paginator = $this->paginate($query, $page);

        return $paginator;
    }

    public function findForSearch($needle, $page)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT g FROM ShopBundle:Gadget g WHERE g.title like :needle or g.manufacturer like :needle"
            )
            ->setParameter('needle', "%$needle%");
        $paginator = $this->paginate($query, $page);

        return $paginator;
    }

    public function paginate($dql, $page = 1, $limit = 12)
    {
        $paginator = new Paginator($dql);
        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return $paginator;
    }
}
