login:
    path:     /login
    defaults: { _controller: ShopBundle:Security:login }
logout:
    path:     /logout

shop_registration:
    path:     /register
    defaults: { _controller: ShopBundle:Security:register }

shop_gadget_search:
    path:     /search/{page}
    defaults: { _controller: ShopBundle:Search:list, page: 1 }

shop_gadget_detail:
    path:     /detail/{id}
    defaults: { _controller: ShopBundle:Gadget:detail }

shop_gadget_list:
    path:     /{page}
    defaults: { _controller: ShopBundle:Gadget:list, page: 1 }

add_basket_item:
    path:     /basket/add
    methods:  'POST'
    defaults: { _controller: ShopBundle:Basket:add }